apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.fullname" . }}-api
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "url-shortener.api.selectorLabels" . | nindent 4 }} 