apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shorturls.urlshortener.tapsi.ir
spec:
  group: urlshortener.tapsi.ir
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              properties:
                targetURL:
                  type: string
              required:
                - targetURL
            status:
              type: object
              properties:
                shortPath:
                  type: string
                clickCount:
                  type: integer
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Target URL
          type: string
          jsonPath: .spec.targetURL
        - name: Short Path
          type: string
          jsonPath: .status.shortPath
        - name: Clicks
          type: integer
          jsonPath: .status.clickCount
  scope: Namespaced
  names:
    plural: shorturls
    singular: shorturl
    kind: ShortURL
    shortNames:
      - surl 