apiVersion: v1
kind: ServiceAccount
metadata:
  name: shorturl-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shorturl-operator-role
rules:
  - apiGroups: ["urlshortener.tapsi.ir"]
    resources: ["shorturls", "shorturls/status"]
    verbs: ["get", "list", "watch", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shorturl-operator-binding
subjects:
  - kind: ServiceAccount
    name: shorturl-operator
roleRef:
  kind: ClusterRole
  name: shorturl-operator-role
  apiGroup: rbac.authorization.k8s.io
